version: "3"
services:
  backend:
    container_name: backend
    image: db_backend
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8888:8888"
    command:
      ${HOST} ${PORT}
