# syntax=docker/dockerfile:1

FROM amd64/python:3.7.14-slim-buster

RUN apt-get update -y
RUN apt-get -y install gcc

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . ./

ENTRYPOINT [ "python3", "main.py"]
